lectures/3/lecture3/hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("brian", views.brian, name="brian"),
    path("david", views.david, name="david"),
    path("<str:name>", views.greet, name="greet")
]

lectures/3/lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('todos/', include("todos.urls"))
]

lectures/3/lecture3/newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index")
]

lectures/3/lecture3/todos/urls.py
from django.urls import path
from . import views

app_name = "todos"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

lectures/3/lecture3/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def brian(request):
    return HttpResponse("Hello, Brian")

def david(request):
    return HttpResponse("Hello, David")

def greet(request, name):
    return render(request, "hello/greet.html", {
        # we create a dictionary including all the variables we want to use
        "name": name.capitalize()
    })

lectures/3/lecture3/newyear/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear":now.month == 1 and now.day == 1
    })

lectures/3/lecture3/todos/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse

class NewTaskForm(forms.Form):
    todo = forms.CharField(label="New todo")
#    priority = forms.IntegerField(label="Priority", min_value=1, max_value=5)

# Create your views here.
def index(request):
    if "todos" not in request.session:
        request.session["todos"] = []
    return render(request, "todos/index.html", {
        "todos": request.session["todos"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            todo = form.cleaned_data["todo"]
            request.session["todos"] += [todo]
            return HttpResponseRedirect(reverse("todos:index"))
        else:
            return render(request, "todos/add.html", {
                "form": form
            })

    return render(request, "todos/add.html", {
        "form": NewTaskForm()
    })

lectures/3/lecture3/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title> Is it New Year's?</title>
        <link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        {% if newyear %}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %}
    </body>
</html>

lectures/3/lecture3/todos/templates/todos/add.html
{% extends "todos/layout.html" %}

{% block body %}

<a href="{% url 'todos:index' %}">Go to todo-list</a> 
<h1>Add task</h1>
<form action="{% url 'todos:add' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>

{% endblock %}

lectures/3/lecture3/todos/templates/todos/index.html
{% extends "todos/layout.html" %}

{% block body %}
<a href="{% url 'todos:add' %}">Add new Task</a> 
<h1>Tasks</h1>
<ul>
    {% for todo in todos %}
    <li> {{todo}}</li>
    {% empty %}
    <li> NO TASKS </li>
    {% endfor %}
</ul>
{% endblock %}

lectures/3/lecture3/todos/templates/todos/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Todos</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>